### PR TITLE
Fix display of variables with = in.

### PR DESCRIPTION
**Pull request by robholland**
Use a character less likely to be in an environment variable.

We're restricted by the fact that `column` can't use a sequence, only a single character. On OS X column won't interpret \t either.

### CODE REVIEW

**Comment by robholland** [comment]
There may be a better character to use? Hard to know what's safe.

**Comment by ayufan** [comment]
Maybe we can use something like: \x01 ?

**Comment by ayufan** [comment]
It's even better. We don't have to use single character. We can use some unique string.

**Comment by robholland** [comment]
Unfortunately column doesn't support a sequence, the -s argument is a set of characters.

echo "xseparatorsxsx" | column -t -s "seperator"
x  x  x

**Comment by ayufan** [comment]
I guess that it should do the work.

**Pull request merged**
